version: "3.5"

networks: 
    app_network:
        name: 'app_backend'
        driver: bridge
services:
    postgres:
        container_name: app_postgres
        image: "postgres:13-alpine"
        environment:
            - POSTGRES_USER=app
            - POSTGRES_DB=coding-challenge-totvs
            - POSTGRES_PASSWORD=app
        ports:
            - "5432:5432"
        networks: 
            - app_network
    app:
        container_name: app_api
        build: .
        image: coding-challenge-totvs
        command: sh -c "adonis migration:run && npm start"
        ports:
            - "3333:3333"
        depends_on: 
            - postgres
        volumes:
            - .:/usr/app
            #Isso exclui o node_modules local e utiliza o instalado no container
            - /usr/app/node_modules
        networks: 
            - app_network 
    app_tests:
        container_name: app_tests
        image: coding-challenge-totvs
        command: npm test
        depends_on: 
            - app
        networks: 
            - app_network 